flight	1	hongkong	paris
flight	2	rome	dublin
flight	3	chicago	newyork
flight	4	cork	cork
flight	5	rome	dublin
flight	6	paris	rome
flight	7	newyork	london
flight	8	amsterdam	rome
flight	9	moscow	dublin
flight	10	dublin	rome
flight	11	newyork	cork
flight	12	rome	berlin
flight	13	cork	moscow
flight	14	dublin	chicago
flight	15	chicago	rome
flight	16	paris	hongkong
flight	17	berlin	rome
flight	18	moscow	rome
flight	19	paris	hongkong
flight	20	hongkong	london
flight	21	london	london
flight	22	paris	dublin
flight	23	berlin	paris
flight	24	cork	cork
flight	25	rome	hongkong
flight	26	dublin	newyork
flight	27	hongkong	dublin
flight	28	amsterdam	paris
flight	29	rome	cork
flight	30	cork	cork
flight	31	newyork	hongkong
flight	32	amsterdam	chicago
flight	33	paris	moscow
flight	34	berlin	paris
flight	35	rome	newyork
flight	36	amsterdam	moscow
flight	37	paris	amsterdam
flight	38	rome	rome
flight	39	moscow	dublin
flight	40	dublin	amsterdam
flight	41	berlin	paris
flight	42	newyork	rome
flight	43	paris	chicago
flight	44	chicago	moscow
flight	45	dublin	chicago
flight	46	hongkong	moscow
flight	47	hongkong	rome
flight	48	chicago	moscow
flight	49	london	cork
flight	50	cork	chicago
flight	51	newyork	paris
flight	52	london	cork
flight	53	hongkong	moscow
flight	54	hongkong	london
flight	55	moscow	cork
flight	56	berlin	dublin
flight	57	newyork	paris
flight	58	rome	berlin
flight	59	moscow	cork
flight	60	moscow	berlin
flight	61	london	dublin
flight	62	rome	chicago
flight	63	cork	paris
flight	64	berlin	amsterdam
flight	65	london	paris
flight	66	chicago	rome
flight	67	newyork	berlin
flight	68	rome	chicago
flight	69	newyork	chicago
flight	70	berlin	newyork
flight	71	dublin	berlin
flight	72	hongkong	newyork
flight	73	cork	newyork
flight	74	rome	hongkong
flight	75	berlin	moscow
flight	76	newyork	moscow
flight	77	dublin	cork
flight	78	cork	cork
flight	79	rome	london
flight	80	rome	london
flight	81	hongkong	london
flight	82	rome	chicago
flight	83	cork	berlin
flight	84	rome	moscow
flight	85	chicago	dublin
flight	86	moscow	rome
flight	87	dublin	amsterdam
flight	88	moscow	london
flight	89	amsterdam	moscow
flight	90	hongkong	moscow
flight	91	berlin	moscow
flight	92	amsterdam	paris
flight	93	rome	london
flight	94	london	newyork
flight	95	london	chicago
flight	96	dublin	newyork
flight	97	paris	berlin
flight	98	paris	rome
flight	99	paris	newyork
flight	100	rome	berlin
flight	101	newyork	rome
flight	102	rome	rome
flight	103	berlin	cork
flight	104	dublin	dublin
flight	105	moscow	hongkong
flight	106	paris	newyork
flight	107	moscow	moscow
flight	108	hongkong	berlin
flight	109	cork	london
flight	110	chicago	moscow
flight	111	rome	berlin
flight	112	rome	hongkong
flight	113	cork	berlin
flight	114	chicago	london
flight	115	rome	newyork
flight	116	newyork	rome
flight	117	newyork	paris
flight	118	paris	hongkong
flight	119	moscow	moscow
flight	120	moscow	chicago
flight	121	newyork	dublin
flight	122	amsterdam	chicago
flight	123	dublin	moscow
flight	124	chicago	amsterdam
flight	125	chicago	paris
flight	126	hongkong	amsterdam
flight	127	moscow	cork
flight	128	berlin	rome
flight	129	chicago	moscow
flight	130	rome	hongkong
flight	131	amsterdam	amsterdam
flight	132	london	amsterdam
flight	133	amsterdam	paris
flight	134	cork	hongkong
flight	135	london	chicago
flight	136	moscow	berlin
flight	137	chicago	hongkong
flight	138	moscow	hongkong
flight	139	amsterdam	chicago
flight	140	newyork	moscow
flight	141	newyork	rome
flight	142	moscow	moscow
flight	143	rome	amsterdam
flight	144	dublin	dublin
flight	145	berlin	newyork
flight	146	amsterdam	berlin
flight	147	amsterdam	rome
flight	148	rome	paris
flight	149	chicago	rome
flight	150	newyork	amsterdam
flight	151	berlin	moscow
